# Generated by Django 3.0.3 on 2020-03-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='score',
            name='times',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='生存时间'),
        ),
    ]
