# Generated by Django 3.0.3 on 2020-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200325_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='slogan',
            field=models.CharField(default='', max_length=30, verbose_name='标语'),
        ),
    ]
