# Generated by Django 3.0.3 on 2020-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_calc', models.BooleanField(default=False, verbose_name='位置计算状态')),
            ],
            options={
                'verbose_name': '开发者',
                'verbose_name_plural': '开发者',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=16, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='slogan',
            field=models.CharField(default='1', max_length=30, verbose_name='标语'),
        ),
    ]
