# Generated by Django 3.0.3 on 2020-03-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200326_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='GameControl',
        ),
        migrations.AlterModelOptions(
            name='gamecontrol',
            options={'verbose_name': '游戏控制', 'verbose_name_plural': '游戏控制'},
        ),
    ]
