# Generated by Django 3.0.3 on 2020-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enermys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_name', models.CharField(max_length=30, verbose_name='敌机编号')),
                ('plane_style', models.FloatField(default=1, verbose_name='敌机类型')),
                ('weapon_style', models.FloatField(default=1, verbose_name='武器类型')),
                ('plane_speed', models.FloatField(default=1, verbose_name='速度')),
                ('plane_angle', models.FloatField(default=0, verbose_name='角度')),
                ('plane_ps_left', models.FloatField(default=0, verbose_name='位置x')),
                ('plane_ps_top', models.FloatField(default=0, verbose_name='位置y')),
                ('plane_life', models.BooleanField(default=False, verbose_name='是否存活')),
            ],
            options={
                'verbose_name': '敌机信息',
                'verbose_name_plural': '敌机信息',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=8, verbose_name='密码')),
                ('truename', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='WeaponStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_0', models.BooleanField(default=True, verbose_name='默认样式')),
                ('weapon_1', models.BooleanField(default=False, verbose_name='样式1')),
                ('weapon_2', models.BooleanField(default=False, verbose_name='样式2')),
                ('weapon_3', models.BooleanField(default=False, verbose_name='样式3')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '武器样式',
                'verbose_name_plural': '武器样式',
            },
        ),
        migrations.CreateModel(
            name='PlaneStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_0', models.BooleanField(default=True, verbose_name='默认样式')),
                ('plane_1', models.BooleanField(default=False, verbose_name='样式1')),
                ('plane_2', models.BooleanField(default=False, verbose_name='样式1')),
                ('plane_3', models.BooleanField(default=False, verbose_name='样式1')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '飞机样式',
                'verbose_name_plural': '飞机样式',
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_style', models.FloatField(default=1, verbose_name='飞机类型')),
                ('weapon_style', models.FloatField(default=1, verbose_name='武器类型')),
                ('plane_speed', models.FloatField(default=1, verbose_name='速度')),
                ('plane_angle', models.FloatField(default=0, verbose_name='角度')),
                ('plane_ps_left', models.FloatField(default=500.0, verbose_name='位置x')),
                ('plane_ps_top', models.FloatField(default=500.0, verbose_name='位置y')),
                ('map_ps_left', models.FloatField(default=-300.0, verbose_name='位置x')),
                ('map_ps_top', models.FloatField(default=-300.0, verbose_name='位置y')),
                ('plane_life', models.BooleanField(default=False, verbose_name='是否存活')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '飞机信息',
                'verbose_name_plural': '飞机信息',
            },
        ),
    ]
