# Generated by Django 3.0.3 on 2020-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_calc', models.BooleanField(default=False, verbose_name='位置计算函数')),
            ],
        ),
    ]
