# Generated by Django 3.0.3 on 2020-02-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_developer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': '开发者', 'verbose_name_plural': '开发者'},
        ),
    ]
