# Generated by Django 3.0.3 on 2020-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200224_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='enermys_create',
            field=models.BooleanField(default=True, verbose_name='敌机生成函数'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='position_calc',
            field=models.BooleanField(default=True, verbose_name='位置计算函数'),
        ),
    ]
