# Generated by Django 3.0.3 on 2020-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200224_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enermys',
            name='plane_name',
        ),
        migrations.AlterField(
            model_name='enermys',
            name='plane_life',
            field=models.BooleanField(default=True, verbose_name='是否存活'),
        ),
    ]
