# Generated by Django 3.0.3 on 2020-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200224_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='enermys_create',
            field=models.BooleanField(default=True, verbose_name='敌机生成状态'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='position_calc',
            field=models.BooleanField(default=True, verbose_name='位置计算状态'),
        ),
    ]
