# Generated by Django 3.0.3 on 2020-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200226_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='enermys_create',
            field=models.BooleanField(default=False, verbose_name='敌机生成状态'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='position_calc',
            field=models.BooleanField(default=False, verbose_name='位置计算状态'),
        ),
    ]
