# Generated by Django 3.0.3 on 2020-02-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200227_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullets_Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_style', models.IntegerField(default=0, verbose_name='默认样式')),
                ('bullet_speed', models.FloatField(default=1, verbose_name='速度')),
                ('bullet_angle', models.FloatField(default=0, verbose_name='角度')),
                ('bullet_ps_left', models.FloatField(default=0, verbose_name='位置x')),
                ('bullet_ps_top', models.FloatField(default=0, verbose_name='位置y')),
                ('bullet_life', models.BooleanField(default=False, verbose_name='是否存活')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '子弹样式',
                'verbose_name_plural': '子弹样式',
            },
        ),
    ]
