# Generated by Django 3.0.3 on 2020-02-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bullets_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='bullets_create',
            field=models.BooleanField(default=False, verbose_name='子弹生成状态'),
        ),
    ]
