# Generated by Django 3.0.3 on 2020-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets_plane',
            name='bullet_speed',
            field=models.FloatField(default=10, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='enermys',
            name='plane_speed',
            field=models.FloatField(default=10, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='planes',
            name='plane_speed',
            field=models.FloatField(default=10, verbose_name='速度'),
        ),
    ]
