# Generated by Django 3.0.3 on 2020-03-12 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('left', models.FloatField(default=0, verbose_name='位置x')),
                ('top', models.FloatField(default=0, verbose_name='位置y')),
                ('speed', models.FloatField(default=0, verbose_name='速度')),
                ('angle', models.FloatField(default=0, verbose_name='角度')),
                ('life', models.BooleanField(default=0, verbose_name='是否生存')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '子弹',
                'verbose_name_plural': '子弹',
            },
        ),
        migrations.CreateModel(
            name='Arrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('left', models.FloatField(default=0, verbose_name='位置x')),
                ('top', models.FloatField(default=0, verbose_name='位置y')),
                ('speed', models.FloatField(default=0, verbose_name='速度')),
                ('angle', models.FloatField(default=0, verbose_name='角度')),
                ('arrow_style', models.IntegerField(default=0, verbose_name='箭头类型')),
                ('weapon_style', models.IntegerField(default=0, verbose_name='武器类型')),
                ('life', models.BooleanField(default=0, verbose_name='是否生存')),
                ('status', models.IntegerField(default=0, verbose_name='箭头状态')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '箭头',
                'verbose_name_plural': '箭头',
            },
        ),
    ]
