# Generated by Django 3.0.3 on 2020-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets',
            name='life',
            field=models.BooleanField(default=True, verbose_name='是否生存'),
        ),
        migrations.AlterField(
            model_name='bullets',
            name='speed',
            field=models.FloatField(default=20, verbose_name='速度'),
        ),
    ]
