# Generated by Django 3.0.3 on 2020-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0002_auto_20200326_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullets',
            name='speed',
            field=models.FloatField(default=16, verbose_name='速度'),
        ),
    ]
